BRS-408 pagination reset after filter update on mobile view
bcgov/bcparks.ca pull request #323
Opened 2022-03-14 20:51 UTC by cameronpettit

### Jira Ticket:
BRS-408

### Jira Ticket URL:
https://bcparksdigital.atlassian.net/browse/BRS-408

### Description:
This change resets the park pagination to page 1 after filters are updated. The `searchFilter` component is used in mobile view which has different handler functions for when a filter is checked/unchecked. This change passes the `setCurrentPage` state function from the explore page to the `searchFilter` component so the currentPage state can be tracked there.

2022-03-14 21:00 UTC, DayKirby-OXD requested changes
Changing filter seems to work as desired, but found a case that's maybe unhandled. In mobile, searched "lake", then went to page 3. Then went to top and searched "mountain", still on page 3

2022-03-14 21:43 UTC, cameronpettit commented
> Changing filter seems to work as desired, but found a case that's maybe unhandled. In mobile, searched "lake", then went to page 3. Then went to top and searched "mountain", still on page 3

This issue was also present while using text search in desktop view. Latest commit should have fixed the issue in desktop view, mobile view, and in the text search in the mobile modal.

2022-03-14 22:54 UTC, DayKirby-OXD approved these changes
Looks good, thx.

2022-03-15 01:36 UTC, marklise approved these changes

2022-03-15 15:37 UTC, merged