BWT-206
bcgov/bcparks.ca pull request #368
Opened 2022-04-27 14:45 UTC by mayurmarakana89

### Jira Ticket:
BWT-206

### Jira Ticket URL:
https://bcparksdigital.atlassian.net/browse/BWT-206

### Description:
Fix reservations notes mismatch in park operation & sub area.

2022-04-27 16:55 UTC, danieltruong approved these changes

2022-04-27 16:57 UTC, marklise requested changes
Please do not submit the first PR with more than 1 commit.  Look into `git rebase -i HEAD~4` && squashing...

2022-04-28 15:59 UTC, marklise commented
Instead of a `merge`, you need to do a `rebase`.  This will avoid this problem:

![image](https://user-images.githubusercontent.com/51633/165794711-772a703b-9391-4362-a2d6-c16e3badf4ea.png)

2022-05-02 18:03 UTC, marklise approved these changes

2022-05-02 18:38 UTC, merged