CM-206: Update park page styling
bcgov/bcparks.ca pull request #491
Opened 2022-12-22 00:05 UTC by ayumi-oxd

### Jira Ticket:
CM-206

### Jira Ticket URL:
https://bcparksdigital.atlassian.net/browse/CM-206

### Description:
- Changed page h2 colour from #000 to #036 (those should be replaced with variables later)
- Added space between the park details and the park contact
- Added the park details header (it can be changed later) to make each section consistent
- Made all bullets aligned

2022-12-22 03:21 UTC, molund approved these changes

2023-01-11 22:07 UTC, foley-lynn requested changes

2023-01-11 22:07 UTC, foley-lynn commented on src/staging/src/styles/parks.scss
>  }
I think you can delete this class after removing it from ~/staging/src/components/park/heading.js

2023-01-11 22:07 UTC, foley-lynn commented on src/staging/src/styles/parks.scss
> +  }
I think we should remove this entire chunk of CSS, and then get rid of the div in ~staging/src/components/park/about.js
<div className="about-details"></div>

There's no reason to style li elements differently here than other places.

2023-01-13 19:50 UTC, foley-lynn approved these changes

2023-01-13 19:50 UTC, foley-lynn commented
Looks great, thanks.

2023-01-13 19:52 UTC, merged